spring.application.name=back-end

spring.datasource.url=jdbc:mysql://172.21.239.87:3306/cms?useSSL=false
spring.datasource.username=root
spring.datasource.password=OHzDE93LJMRakxOKhxxuxVqo
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:oL979RtXRjWai11spfigOT4s@172.21.71.236:27017/prescriptions?authSource=admin

spring.web.resources.static-locations=classpath:/static/

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

jwt.secret=SmartClinicJWTSecretKey2026Secure123456789

api.path=/